# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dabba9875a9f935d38ea69c6d833df7706616eba2deec1dc9fd556d49cc806d09c5d7fe2fa88830e511d33a8f99f440ee87d350c26949d616ee08cf7ebae16d9

test:
  secret_key_base: 4e2a1f842dfb4840470290a9b190fd8024fa2bc16916d84efad500853148b925dae14e8474a2912dfa78b441218d48b9ea7458d3558f406170408cdcdb31029d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
